### ISSUE TITLE
Homebrew not managing dependencies correctly

### ISSUE THREAD

**Issue by dmytroyaremyshyn** [Backbase/variants#113]
When I try `brew install variants` I get an error: Error: Your Xcode (12.0) is outdated.
UPDATE: I updated my Xcode to the latest version and now the error is :  "xcrun: error: unable to find utility "xctest", not a developer tool or in PATH"

**Comment by arthurpalves** [comment]
We should remove this dependency from the homebrew formula

**Comment by arthurpalves** [comment]
It has been removed https://github.com/Backbase/homebrew-m/commit/5f2b05f143d4171053fc5cb63c1aaf55bc72c5e6

**Comment by nascimentorafael** [comment]
`brew install backbase/m/variants`

Works here.

**Comment by arthurpalves** [comment]
@dmytroyaremyshyn if it happens again you can reopen the issue, I'll close it for now.
