### ISSUE TITLE
Android signing

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#123]
Investigate whether variants could be used also for handling android signing

**Comment by arthurpalves** [comment]
Prio set to "high"  for 1.0.0 release, as we need the outcome of this investigation in order to achieve this or remove the current implementation of `android.signing` that is available but doesn't really do anything.

**Comment by gderaco** [comment]
I have thought about this and I think it's better to leave as it is: the signing will be handled on the project level through the build.gradle script. The signing of the app is strictly connected to the build type which is part of the Gradle task Variants executes.

I will polish the code so there will be no mention of the android signing.
