### ISSUE TITLE
Expose configuration keys as static variables in swift 

### ISSUE THREAD

**Issue by DanielSumara** [Backbase/variants#125]
`variants` generate `Variants` structure for iOS project. This struct contains encrypted env variables which we can access in safe manner using eg. `print(Variants. Secrets.propertyName)`. [ENVIRONMENT VARIABLES](https://github.com/Backbase/variants/blob/develop/docs/ENVIRONMENT_VARIABLES.md)

It would be great improvement if we could access in the same manner other defined properties instead using string as keys.

We can replace `print(Variants.configuration["A_PROPERTY"])` using `(Variants.configuration[.aProperty])`

**Comment by gderaco** [comment]
Be sure to keep the old way to guarantee retrocompatibility
