### ISSUE TITLE
Bug: Build failling in the CI workflow

### ISSUE THREAD

**Issue by GMinucci** [Backbase/variants#160]
# Basic information
The CI is currently failing in the develop branch as there is no Xcode 12 in MacOS 11 machines anymore.
The list of available Xcode application versions can be found [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md).

Variants version: 1.0.0
macOS version: macOS 11.6
Swift version: Not applicable

**Comment by obackbase** [comment]
According to the last build status, CI workflow fixed: https://github.com/Backbase/variants/actions/runs/1979899910
