### ISSUE TITLE
 Templates folder not found in /usr/local/lib/variants/templates or ./Templates

### ISSUE THREAD

**Issue by dcalbert** [Backbase/variants#177]
I have installed two different ways. One with homebrew and the other as the CLI (Swift Package Manager).  If I run `variants init` for  both installs, then I get `Error: ❌ Templates folder not found in /usr/local/lib/variants/templates or ./Templates`.  If i run `variants switch --variant default`, then I get `"⚠️  Something went wrong while generating 'Variants.Secrets' in '/Users/...'`
▿ ❌ Templates folder not found in /usr/local/lib/variants/templates or ./Templates
  - description: "❌ Templates folder not found in /usr/local/lib/variants/templates or ./Templates" ".  
 

I have an apple silicon macbook.  The only installation that didn't produce an error message is the Make installation.

**Comment by gderaco** [comment]
Do you still face the issue? Did you try to use Variants 1.1.0?

Can you please provide:
Variants version
iOS / Android
