### ISSUE TITLE
Automate the generation of brew bottles when a new release is created

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#182]
## Background
As of now, if you want to create the bottles, it is something that developers need to do locally: they need to create the bottle with `brew bottle variants` and then upload the files in the release's attachment.

## Solution
Use a pipeline to do that, so it's not longer a human action, [this tool](https://docs.brew.sh/Brew-Test-Bot) can be used.

**Comment by arthurpalves** [comment]
This has been done in our [Tap](https://github.com/Backbase/homebrew-m/blob/master/.github/workflows/manual_release.yaml#L73-L85) with the help of this [homebrew fork](https://github.com/Backbase/bottler) I made
