### ISSUE TITLE
Investigate about the removal of gitleaks

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#183]
## Background

Gitleaks became a pay tool.

## Solution

Find a free solution

**Comment by rkyaganti** [comment]
@arthurpalves @gderaco @GMinucci 

Please consider below open source solutions as an alternative

**GitGuardian**: GitGuardian is a free and open-source solution that helps developers detect and prevent secrets and credentials from being leaked in Git repositories. It supports multiple Git platforms including GitHub, GitLab, and Bitbucket.

**TruffleHog**: TruffleHog is another open-source tool that scans Git repositories to identify secrets, API keys, and other sensitive information. It is easy to use and can be integrated into your CI/CD pipeline.

**Gitrob**: Gitrob is a command-line tool that scans Git repositories for sensitive files and data. It can identify usernames, email addresses, and other information that could be used for social engineering attacks.

**Shhgit**: Shhgit is a tool that scans Git repositories for secrets and sensitive information. It is free to use and can be integrated with Slack, Discord, and other communication tools to notify you of potential security issues.

**Comment by GMinucci** [comment]
Another update:
It seems that gitleaks is free for organization accounts so we will apply for a key here and keep gitleaks.
https://gitleaks.io/products.html
