### ISSUE TITLE
Create template for issues

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#185]
Create GitHub template for issues that has the following information to be provided:

- Variants version
- Execution Operating System
- Intel or Silicon
- Way of installation
- iOS / Android

**Comment by romanhu-bb** [comment]
For now it will be issue template, but later it can be made as issue form once its not in beta
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
