### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by gderaco** [Backbase/variants#45]
Check if _variant_ works on _linux_. If not, apply the necessary changes. Windows users can use _variant_ on Linux through Docker.

**Comment by obackbase** [comment]
Tried to run on Ubuntu (linux-docker-android-20.04)

```
Cloning into 'variants'...
/bin/bash: swift: command not found
make: *** [Makefile:23: variants] Error 127
```

**Comment by gderaco** [comment]
@obackbase on Linux you need to install swift first or you can use a Docker image that has swift
