### ISSUE TITLE
Android AppCenter template is broken

### ISSUE THREAD

**Issue by BBWillNasby** [Backbase/variants#95]
The AppCenter template imports `parameters/appcenter_params.rb` to retrieve the variable `APPCENTER_APP_NAME`. The problem is, the only way to configure your variant to add the app name, is to set the destination to `fastlane` which places the `APPCENTER_APP_NAME` in `variants_params.rb`.

So, we can either fix the template, changing appcenter_params reference to variants_params, or we need to add the ability for a user to set the destination for a variable to appcenter_params.

**Comment by arthurpalves** [comment]
Hey @BBWillNasby! 👋

It is actually correct.
See `appcenter_params.rb` as containing information that won't change depending on which variant of your app you deploy to AppCenter. While `variants_params.rb` will contain the variant's specific information.

The file [fastlane/AppCenter](https://github.com/Backbase/variants/blob/develop/Templates/android/_fastlane/fastlane/AppCenter) imports `appcenter_params.rb` and uses values from it (lines 19, 23 and 24). The app name however is expected to be on `variants_params.rb`. For this reason, we must simply provide a documentation on `"How to deploy to AppCenter"`, stating that in this case you should provide a custom property named `APPCENTER_APP_NAME` with destination `fastlane` whenever `store_destination` is set to `AppCenter`.

Also, the reason that [fastlane/AppCenter](https://github.com/Backbase/variants/blob/develop/Templates/android/_fastlane/fastlane/AppCenter) doesn't import `variants_params.rb` as it does for `appcenter_params.rb` is that the first has already been imported by [fastlane/Fastfile](https://github.com/Backbase/variants/blob/develop/Templates/android/_fastlane/fastlane/Fastfile).

**Comment by BBWillNasby** [comment]
@arthurpalves 

Ah, I remember now you explained it to me in your PR, my bad.
